
GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Yakuba Swaray",
  "username": "yaqoub",
  "password": "yakub09"
}


###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Alusine Swaray",
  "username": "ray",
  "password": "ray8542"
}

